### ISSUE TITLE
PS v6.0 Alpha : Remove-Item : The process cannot access the file

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/Plaster#240] opened 2017-03-09 16:39 UTC
When I run several times this template : plaster\1.0.1\Templates\NewPowerShellManifestModule
I get an exception : _'Remove-Item : The process cannot access the file
'C:\Users\Laurent\AppData\Local\Temp\moduleManifest-c78732c2-851e-4e86-a32a-9d527b16ed39.psd1' because it is being used by another process.'_

![image](https://cloud.githubusercontent.com/assets/4894452/23759619/91d2848c-04ed-11e7-8850-6b2c16747f3b.png)

When I delete all files in the DestinationPath and run again the same template, I get this exception :
_'Copy-Item : The process cannot access the file 'C:\temp\TestPlaster\test\test.Tests.ps1' because it is being used by another process.'_
![image](https://cloud.githubusercontent.com/assets/4894452/23759936/7077ff96-04ee-11e7-8a8c-238944746922.png)

```Powershell
#Windows Seven
$PSVersiontable
Name                           Value
----                           -----
CLRVersion
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.16
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
PSEdition                      Core
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment] 2017-03-31 15:12
I can repro this one.  I'll look into it.

**Comment by larssb** [comment] 2017-06-27 14:13
@LaurentDardenne can you still produce this on beta3 of PowerShell v6? Maybe we can save the Plaster team some work if it's not an issue anymore. My approach to writing on this issue.

**Comment by LaurentDardenne** [comment] 2017-06-28 10:35
Same error, the fisrt installation is correct, but not the second :
![image](https://user-images.githubusercontent.com/4894452/27631780-e51a0742-5bf9-11e7-9554-3d5a0b6cac7f.png)

I close the current PS session(powershell.exe) and run a new session  :
![image](https://user-images.githubusercontent.com/4894452/27631848-3b8d0d86-5bfa-11e7-88ff-a1b7037fe2ac.png)
The contains of $Error : 
```powershell
PS C:\program files\powershell\6.0.0-beta.3\Modules\plaster\1.0.1\Templates\NewPowerShellManifestModule> $Error
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to
Stop: The process cannot access the file
'C:\Users\laurent\AppData\Local\Temp\2\moduleManifest-f39f6cae-d3c6-429f-8c0e-4594d07233c0.psd1' because it is being
used by another process.
Remove-Item : The process cannot access the file
'C:\Users\laurent\AppData\Local\Temp\2\moduleManifest-f39f6cae-d3c6-429f-8c0e-4594d07233c0.psd1' because it is being
used by another process.
At C:\program files\powershell\6.0.0-beta.3\Modules\plaster\1.0.1\InvokePlaster.ps1:820 char:25
+                         Remove-Item -LiteralPath $tempFile
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\lauren...94d07233c0.psd1:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand

Copy-Item : The process cannot access the file 'C:\temp\Plastertest\test.psd1' because it is being used by another
process.
At C:\program files\powershell\6.0.0-beta.3\Modules\plaster\1.0.1\InvokePlaster.ps1:979 char:21
+ ...                 Copy-Item -LiteralPath $SrcPath -Destination $DstPath
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand
```
I remove the destination path, the installation works fine.

One more time  :
![image](https://user-images.githubusercontent.com/4894452/27632709-da306c7e-5bfc-11e7-91e9-0ac6ec93604d.png)

This files are really locked, after a delay (1 mn -2 mn) i can delete the temporary file but not the psd1 : 

![image](https://user-images.githubusercontent.com/4894452/27633067-02ed8fa6-5bfe-11e7-8eec-0d0c223e77e0.png)

I thinks is it a Powershell bug.

```Powershell
$psversiontable (Windows server 2016) :

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by larssb** [comment] 2017-06-28 13:13
@LaurentDardenne dang you can. Okay, but good to know. @rkeithhill do you think this should also be reported in Microsofts powershell github repo? Or did the data you got when reproducing this tell you that this is something the Plaster project has to/can fix within its boundaries?

**Comment by rkeithhill** [comment] 2017-06-28 14:52
When I repro'd it, I assumed that this was an issue with either early .NET Core bits or PowerShell Core bits.  But before submitting an issue to these projects, I need to track exactly where the problem lies to make sure it isn't a Plaster issue.

**Comment by larssb** [comment] 2017-06-28 16:48
Sure :-)

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -

**Comment by rkeithhill** [comment] 2017-07-02 00:04
This appears to be a problem with the PowerShell Core `Get-FileHash` command.  It seems to be leaving open a file handle to the file it is passed.

**Comment by rkeithhill** [comment] 2017-07-02 00:24
OK, I've submitted a [PR](https://github.com/PowerShell/PowerShell/pull/4175) to fix the issue with `Get-FileHash` and from my testing it fixes the issue as you see it from Plaster.   I'm confident enough in the fix to close the issue here.

**Closed by rkeithhill** 2017-07-02 00:24 UTC
Labels: area-cross-platform, bug

**Comment by LaurentDardenne** [comment] 2017-07-02 06:14
Thanks Keith :-)

**Comment by rkeithhill** [comment] 2017-07-07 17:04
That PR has been merged into PowerShell Core.  Running Plaster with PS Core Beta.4 should no longer exhibit this issue.
